#!/usr/bin/env python3
"""
Define a coroutine containing an async
comprehension over another async
coroutine.
"""
import asyncio
from typing import List


async def async_comprehension() -> List[float]:
    """
    Obtain nuumbers generated by an async
    generator.

    Returns:
        A list of random numbers collected
        from the async generator.
    """
    async_gen = __import__("0-async_generator").async_generator
    return ([item async for item in async_gen()])
